from dataclasses import dataclass
from typing import Optional, List, Callable, Any


@dataclass
class ConceptDefinition:
    name: str
    datatype: Optional[str] = None


def validate_concept(concept_data: dict) -> bool:
    """
    Main validation function that checks if concept exists and has required fields
    This is the function that will be used by default in the main script
    """
    return True


def default_concept_validator(concept_data: dict) -> bool:
    """
    Default validation function that checks if concept exists and has required fields
    """
    return (
        concept_data is not None
        and "uuid" in concept_data
        and concept_data.get("uuid") is not None
    )


# Example concept names array
CONCEPT_NAMES = [
    "A00 Cholera",
    "A01 Typhoid and paratyphoid fevers",
    "A02 Other infections caused by Salmonella",
    "A02.1 Salmonella septicemia",
    "A03 Shigellosis",
    "A04 Other bacterial intestinal infections",
    "A05.9 Bacterial foodborne intoxication, unspecified",
    "A09 Diarrhea and gastroenteritis of presumed infectious origin",
    "A15 Pulmonary tuberculosis with bacteriological and histological confirmation",
    "A15.0 Pulmonary tuberculosis confirmed by microscopic examination of sputum with or without culture",
    "A16.5 Tuberculous pleurisy (without mention of bacteriological or histological confirmation)",
    "A17.0 Tuberculous meningitis",
    "A18.3 Tuberculosis of the intestines, peritoneum, and mesenteric lymph nodes",
    "A18.8 Tuberculosis of other specified organs",
    "A19 Miliary tuberculosis",
    "A20 Plague",
    "A22 Anthrax",
    "A21 Tularemia",
    "A30 Leprosy [Hansen's disease]",
    "A31 Infections due to other mycobacteria",
    "A32 Listeriosis",
    "A32.1 Listerial meningitis and meningoencephalitis",
    "A33 Neonatal tetanus",
    "A34 Obstetric (maternal) tetanus",
    "A36 Diphtheria",
    "A35 Other forms of tetanus",
    "A37 Whooping cough",
    "A39 Meningococcal infection",
    "A39.5 Meningococcal carditis",
    "A40 Streptococcal septicemia",
    "A41 Other septicemias",
    "A41.3 Haemophilus influenzae septicemia",
    "A42 Actinomycosis",
    "A46 Erysipelas",
    "A48 Other bacterial diseases not classified elsewhere",
    "A50 Congenital syphilis",
    "A56 Other Chlamydia infections transmitted sexually",
    "A54 Gonococcal infection",
    "A55 Lymphogranulomatosis venereum due to Chlamydia",
    "A57 Soft chancre",
    "A59.0 Urogenital trichomoniasis",
    "A60 Genital herpes simplex infection",
    "A63 Other diseases predominantly transmitted sexually not classified elsewhere",
    "A63.0 Anogenital condylomas (venereal)",
    "A65 Non-venereal syphilis",
    "A69 Other infections caused by spirochetes",
    "A69.0 Ulceronecrotic stomatitis",
    "A70 Chlamydia psittaci infection",
    "A71 Trachoma",
    "A74 Other Chlamydia infections",
    "A74.0 Chlamydia conjunctivitis",
    "A75 Typhus Viral infections of the central nervous system",
    "A80 Acute poliomyelitis",
    "A82 Human rabies",
    "A87 Viral meningitis",
    "A85.0 Enterovirus encephalitis",
    "A88 Other viral infections of the central nervous system not classified elsewhere",
    "B00.5 Eye disorders due to herpes virus",
    "A98 Other viral hemorrhagic fevers not classified elsewhere",
    "B00.0 Herpetic eczema",
    "2017-A98.4 Ebola virus disease",
    "B00 Herpes virus infections [herpes simplex]",
    "B03 Smallpox",
    "B01 Chickenpox",
    "B08.1 Molluscum contagiosum",
    "B08.5 Vesicular pharyngitis due to an enterovirus",
    "B02 Shingles [herpes zoster]",
    "B08 Other viral infections characterized by cutaneous-mucosal lesions not elsewhere classified",
    "B21.0 HIV disease resulting in Kaposi's sarcoma",
    "B22.0 HIV disease resulting in encephalopathy",
    "B23.0 Acute HIV infection syndrome",
    "B25 Cytomegalovirus disease",
    "B26 Mumps",
    "B35 Dermatophytosis",
    "B27 Infectious mononucleosis",
    "B37 Candidiasis",
    "B37.2 Candidiasis of the skin and nails",
    "B37.3 Vulvar and vaginal candidiasis",
    "B37.4 Candidiasis of other urogenital locations",
    "B38 Coccidioidomycosis",
    "B45 Cryptococcosis",
    "B45.1 Cerebral cryptococcosis",
    "B50 Malaria due to Plasmodium falciparum",
    "B50.0 Malaria due to Plasmodium falciparum with cerebral complications",
    "B53 Other confirmed malaria",
    "B58 Toxoplasmosis",
    "B68 Infection by Taenia",
    "B65 Schistosomiasis",
    "B73 Onchocerciasis",
    "B77 Ascariasis",
    "B85 Pediculosis and phthiriasis",
    "B80 Enterobiasis",
    "B86 Scabies",
    "B87 Myiasis",
    "B881 Tungiasis",
    "B949 Sequelae of infectious or parasitic disease, unspecified",
    "B99 Other specified infectious diseases",
    "C Malignant neoplasm of the ampulla of Vater",
    "C00 Malignant neoplasm of the lip",
    "C01 Malignant tumor of the base of the tongue",
    "C02 Malignant tumor of the tongue, other and unspecified parts",
    "C03 Malignant tumor of the gums",
    "C04 Malignant tumor of the floor of the mouth",
    "C05 Malignant tumors of the mouth, other and unspecified parts",
    "C07 Malignant tumor of the parotid gland",
    "C14.0 Pharynx, unspecified",
    "C16 Malignant tumor of the stomach",
    "C15 Malignant tumor of the esophagus",
    "C17 Malignant tumor of the small intestine",
    "C18 Malignant tumor of the colon",
    "C19 Malignant tumor of the recto-sigmoid junction",
    "C20 Malignant tumor of the rectum",
    "C21 Malignant tumors of the anus and anal canal",
    "C22.0 Hepatocellular carcinoma",
    "C22.9 Liver, unspecified",
    "C23 Malignant tumor of the gallbladder",
    "C25 Malignant tumor of the pancreas",
    "C26 Malignant tumor of the digestive organs, other and ill-defined sites",
    "C30 Malignant tumor of the nasal cavities and middle ear",
    "C32 Malignant tumor of the larynx",
    "C33 Malignant tumor of the trachea",
    "C38 Malignant tumor of the heart, mediastinum, and pleura",
    "C40 Malignant tumor of the bones and articular cartilage of the limbs",
    "C41 Malignant tumor of the bone and articular cartilage of unspecified site",
    "C43 Malignant melanoma of the skin",
    "C44 Other malignant tumors of the skin",
    "C45 Mesothelioma",
    "C46 Kaposi sarcoma, including morphological code M9140 with behavior code/3 not associated with HIV",
    "C47 Malignant tumor of the peripheral nerves and autonomic nervous system",
    "C48 Malignant tumor of the retroperitoneum and peritoneum",
    "C50 Malignant tumor of the breast",
    "C51 Malignant tumor of the vulva",
    "C52 Malignant tumor of the vagina",
    "C53 Malignant tumor of the cervix",
    "C54 Malignant tumor of the body of the uterus",
    "C56 Malignant tumor of the ovary",
    "C58 Malignant tumor of the placenta",
    "C60 Malignant tumor of the penis",
    "C61 Malignant tumor of the prostate",
    "C62 Malignant tumor of the testis",
    "C64 Malignant tumor of the kidney, except the renal pelvis",
    "C67 Malignant tumor of the bladder",
    "C69 Malignant tumor of the eye and its adnexa",
    "2017-C70 Malignant tumor of the meninges",
    "C71 Malignant tumors of the brain",
    "C72 Malignant tumors of the spinal cord, cranial nerves, and other parts of the central nervous system",
    "C73 Malignant tumor of the thyroid",
    "2017-C74 Malignant tumor of the adrenal gland",
    "C77 Malignant tumor of lymph nodes, secondary and unspecified",
    "C78 Secondary malignant tumor of the respiratory and digestive organs",
    "C79 Secondary malignant tumors in other locations",
    "C80 Malignant tumor of unspecified site",
    "C81 Hodgkin's disease",
    "C82 Non-Hodgkin follicular lymphoma",
    "C83 Diffuse non-Hodgkin lymphoma",
    "C83.7 Burkitt's tumor",
    "C84 Peripheral and cutaneous T-cell lymphoma",
    "C90 Multiple myeloma and malignant plasma cell tumors",
    "C92 Myeloid leukemia",
    "D00 Carcinoma in situ of the oral cavity, esophagus, and stomach",
    "C93 Monocytic leukemia",
    "C96 Malignant tumors of hematopoietic and lymphoid tissue and related unspecified",
    "D02 Carcinoma in situ of the middle ear and respiratory system",
    "D03 Melanoma in situ",
    "D04 Carcinoma in situ of the skin",
    "D05 Carcinoma in situ of the breast",
    "D15 Benign tumor of other and unspecified intrathoracic organs",
    "D06 Carcinoma in situ of the cervix",
    "D07 Carcinoma in situ of other and unspecified genital organs",
    "D09 Carcinoma in situ of other and unspecified sites",
    "D10 Benign tumor of the mouth and pharynx",
    "D11 Benign tumor of the major salivary glands",
    "D13 Benign tumors of other and poorly defined parts of the digestive system",
    "D12 Benign tumor of the colon, rectum, anus, and anal canal",
    "D14 Benign tumor of the middle ear and respiratory system",
    "D18 Hemangioma and lymphangioma of any site",
    "D16 Benign tumor of the bones and joint cartilage",
    "D17 Benign lipomatous tumor",
    "D21 Other benign tumors of connective tissue and other soft tissues",
    "D22 Nevus of melanocytes",
    "D23 Other benign tumors of the skin",
    "D24 Benign tumor of the breast",
    "D25 Uterine leiomyoma",
    "D27 Benign tumor of the ovary",
    "D28 Other and unspecified benign tumors of the female genital organs",
    "D29 Benign tumor of the male genital organs",
    "D30 Benign tumor of the urinary organs",
    "D31 Benign tumor of the eye and its appendages",
    "D32 Benign tumor of the meninges",
    "D33 Benign tumor of the brain and other parts of the central nervous system",
    "D34 Benign tumor of the thyroid",
    "D35 Other and unspecified benign tumors of the endocrine glands",
    "D39 Tumor of the female genital organs with unpredictable or unknown behavior",
    "D36 Benign tumors of other and unspecified sites",
    "D40 Tumor of the male genital organs with unpredictable or unknown behavior",
    "D45 Essential polycythemia",
    "D44 Tumor of the endocrine glands with unpredictable or unknown behavior",
    "D46 Myelodysplastic syndromes",
    "D50 Iron deficiency anemia",
    "D50.0 Iron deficiency anemia due to chronic blood loss",
    "D50.9 Iron deficiency anemia unspecified",
    "D51 Vitamin B12 deficiency anemia",
    "D52 Folic acid deficiency anemia",
    "D53 Other nutritional anemias",
    "D55 Anemia due to enzymatic anomalies",
    "D56 Thalassemia",
    "D55.0 Anemia due to glucose-6-phosphate dehydrogenase deficiency",
    "2017-D56.1 Beta-thalassemia",
    "D57.0 Anemia with sickle-shaped red blood cells (sickle cell anemia)",
    "D58.8 Other specified hereditary hemolytic anemias",
    "D59 Acquired hemolytic anemia",
    "D61 Other bone marrow aplasias",
    "D61.0 Constitutional bone marrow aplasia",
    "D61.1 Drug-induced bone marrow aplasia",
    "D61.2 Bone marrow aplasia due to other external agents",
    "D63 Anemia in the context of chronic diseases classified elsewhere",
    "D61.3 Idiopathic bone marrow aplasia",
    "D63.0 Anemia in the context of neoplastic diseases",
    "D63.8 Anemia in the context of other chronic diseases classified elsewhere",
    "D65 Disseminated intravascular coagulation [defibrination syndrome]",
    "D69 Purpura and other hemorrhagic conditions",
    "D69.6 Thrombocytopenia unspecified",
    "D70 Agranulocytosis",
    "D73.2 Chronic congestive splenomegaly",
    "D75 Other diseases of blood and blood-forming organs",
    "D75.1 Secondary polycythemia",
    "D80 Immunodeficiency with predominant antibody production deficiency",
    "D84 Other immunodeficiencies",
    "D84.9 Immunodeficiency unspecified",
    "D86 Sarcoidosis",
    "E01.0 Diffuse (endemic) goiter related to iodine deficiency",
    "E00 Congenital hypothyroid syndrome",
    "E03 Other hypothyroid conditions",
    "E04 Other non-toxic goiters",
    "E05 Thyrotoxicosis [hyperthyroidism]",
    "E06 Thyroiditis",
    "E06.0 Acute thyroiditis",
    "E06.1 Subacute thyroiditis",
    "E07 Other thyroid conditions",
    "E10 Insulin-dependent diabetes mellitus",
    "E10.6 Insulin-dependent diabetes mellitus with specified complications",
    "E11 Non-insulin-dependent diabetes mellitus",
    "E11.6 Non-insulin-dependent diabetes mellitus with specified complications",
    "E12 Malnutrition-related diabetes mellitus",
    "E15 Non-diabetic hypoglycemic coma",
    "E16.0 Drug-induced hypoglycemia without coma",
    "E16.1 Other hypoglycemia",
    "E20 Hypoparathyroidism",
    "E22 Pituitary hypersecretion",
    "E24 Cushing's syndrome",
    "E28 Ovarian dysfunction",
    "E29 Testicular dysfunction",
    "E30 Pubertal anomalies not elsewhere classified",
    "E31 Polyglandular dysfunction",
    "E34 Other endocrine disorders",
    "E34.3 Unspecified growth failure",
    "E43 Severe protein-energy malnutrition unspecified",
    "E40 Kwashiorkor",
    "E41 Nutritional marasmus",
    "E73 Lactose intolerance",
    "E44 Mild or moderate protein-energy malnutrition",
    "E65 Localized obesity",
    "E51 Thiamine deficiency",
    "E63 Other nutritional deficiencies",
    "E63.1 Nutritional imbalance",
    "E66.9 Obesity unspecified",
    "E78 Lipoprotein metabolism disorders and other lipidemias",
    "E84 Cystic fibrosis",
    "2017-E85 Amyloidosis",
    "E86 Hypovolemia",
    "E87 Other hydro-electrolytic and acid-base imbalances",
    "F03 Unspecified dementia",
    "E87.2 Acidosis",
    "E89 Endocrine and metabolic disorders following diagnostic and therapeutic procedures not elsewhere classified",
    "F00 Dementia due to Alzheimer's disease",
    "F09 Organic or symptomatic mental disorder unspecified",
    "F04 Organic amnestic syndrome not induced by alcohol and other psychoactive substances",
    "F17 Mental and behavioral disorders due to tobacco use",
    "F05 Delirium not induced by alcohol and other psychoactive substances",
    "F10 Mental and behavioral disorders due to alcohol use",
    "F11 Mental and behavioral disorders due to opioid use",
    "F12 Mental and behavioral disorders due to cannabis derivatives use",
    "F20 Schizophrenia",
    "F23 Acute and transient psychotic disorders",
    "F25 Schizoaffective disorders",
    "F30 Manic episode",
    "F31 Bipolar affective disorder",
    "F32 Depressive episodes",
    "F34 Persistent mood [affective] disorders",
    "F38 Other mood [affective] disorders",
    "F40 Phobic anxiety disorders",
    "F41 Other anxiety disorders",
    "F42 Obsessive-compulsive disorder",
    "F43 Reaction to severe stress and adjustment disorders",
    "F44 Dissociative disorders [conversion disorders]",
    "F45 Somatoform disorders",
    "F48 Other neurotic disorders",
    "F50 Eating disorders",
    "F50.0 Anorexia nervosa",
    "F50.1 Bulimia",
    "F50.5 Vomiting associated with other psychological disturbances",
    "F50.8 Other eating disorders",
    "F51 Non-organic sleep disorders",
    "F52 Sexual dysfunction not due to a disorder or organic disease",
    "F52.0 Absence or loss of sexual desire",
    "F52.1 Sexual aversion and lack of sexual pleasure",
    "F52.2 Genital response failures",
    "F52.3 Orgasmic dysfunction",
    "F52.5 Non-organic vaginismus",
    "F52.4 Premature ejaculation",
    "F52.6 Non-organic dyspareunia",
    "F52.7 Excessive sexual activity",
    "F52.8 Other sexual dysfunctions not due to a disorder or organic disease",
    "F52.9 Sexual dysfunction not due to a disorder or organic disease, unspecified",
    "F53 Mental and behavioral disorders associated with the puerperium not classified elsewhere",
    "F54 Psychological and behavioral factors associated with diseases or disorders classified elsewhere",
    "2017-F55 Substance abuse not resulting in dependence",
    "F60 Specific personality disorders",
    "F63.0 Pathological gambling",
    "F63 Disorders of habit and impulse",
    "F65 Sexual preference disorders",
    "2017-F63.1 Pathological tendency to set fires (pyromania)",
    "2017-F63.3 Trichotillomania",
    "F64 Gender identity disorder",
    "F70 Mild intellectual disability",
    "F71 Moderate intellectual disability",
    "F80 Specific development disorders of speech and language",
    "F84 Pervasive developmental disorders",
    "F90 Hyperkinetic disorders",
    "F91 Conduct disorders",
    "F92 Mixed conduct and emotional disorders",
    "F95 Tics",
    "F98 Other behavioral and emotional disorders usually occurring in childhood and adolescence",
    "F98.0 Non-organic enuresis",
    "F98.2 Feeding disorder of infancy or childhood",
    "2017-F98.5 Stuttering",
    "F99 Mental disorder, unspecified",
    "G00.0 Haemophilus meningitis",
    "G00.1 Pneumococcal meningitis",
    "G00.9 Bacterial meningitis unspecified",
    "G03.0 Clear fluid meningitis",
    "G04 Encephalitis, myelitis, and encephalomyelitis",
    "G06 Intracranial and intradural abscess and granuloma",
    "G20 Parkinson's disease",
    "G21 Secondary parkinsonian syndrome",
    "G21.0 Neuroleptic malignant syndrome",
    "G25 Other extrapyramidal syndromes and movement disorders",
    "G25.0 Essential tremor",
    "G30 Alzheimer's disease",
    "G35 Multiple sclerosis",
    "G40 Epilepsy",
    "G43 Migraine",
    "G44 Other headache syndromes",
    "G44.0 Cluster headache",
    "G44.1 Unclassified vascular headache",
    "G44.2 Tension-type headache",
    "G44.3 Chronic post-traumatic headache",
    "G47 Sleep disorders",
    "G45 Transient ischemic attacks and related syndromes",
    "G58 Other mononeuritis",
    "G50.1 Atypical facial pain",
    "G51 Facial nerve disorders",
    "G52 Disorders of other cranial nerves",
    "G56 Mononeuritis of the upper limb",
    "G56.0 Carpal tunnel syndrome",
    "G54 Disorders of nerve roots and plexuses",
    "G71 Primary muscle disorders",
    "G80 Cerebral palsy",
    "G81 Hemiplegia",
    "G82 Paraplegia and tetraplegia",
    "G91 Hydrocephalus",
    "G83 Other paralytic syndromes",
    "G93 Other brain disorders",
    "G93.3 Post-viral fatigue syndrome",
    "G97 Nervous system disorders after a diagnostic and therapeutic procedure not elsewhere classified",
    "G97.8 Other nervous system disorders after a diagnostic and therapeutic procedure",
    "H00 Stye and chalazion",
    "H02 Other eyelid disorders",
    "H06 Diseases of the lacrimal apparatus and orbit occurring in diseases classified elsewhere",
    "H04 Diseases of the lacrimal apparatus",
    "H01 Other inflammations of the eyelid",
    "H10 Conjunctivitis (collected in hospitals)",
    "H11 Other conditions of the conjunctiva",
    "H11.0 Pterygium",
    "H11.3 Conjunctival hemorrhage",
    "H15 Diseases of the sclera",
    "H16 Keratitis",
    "H17 Scars and opacities of the cornea",
    "H18 Other conditions of the cornea",
    "H20 Iridocyclitis",
    "H25 Senile cataract",
    "H26 Other cataracts",
    "H27 Other conditions of the lens",
    "H30 Chorioretinitis",
    "H32 Other chorioretinal conditions occurring in diseases classified elsewhere",
    "H33 Retinal detachment and tear",
    "H34 Retinal vascular occlusions",
    "H36 Retinal diseases occurring in diseases classified elsewhere",
    "H35 Other retinal conditions",
    "H40 Glaucoma",
    "H43 Conditions of the vitreous body",
    "H44 Conditions of the eyeball",
    "H46 Optic neuritis",
    "H47 Other conditions of the optic nerve and visual pathways",
    "H49 Paralytic strabismus",
    "H50 Other strabismus",
    "H51 Other binocular movement abnormalities",
    "H52 Refractive errors and accommodation disorders",
    "H53 Vision disorders",
    "H54 Blindness and vision loss",
    "H55 Nystagmus and other ocular movement anomalies",
    "H57 Other conditions of the eye and its appendages",
    "H59 Conditions of the eye and its appendages after a diagnostic or therapeutic procedure not classified elsewhere",
    "H60 External otitis",
    "H61 Other conditions of the external ear",
    "H62 Conditions of the external ear in the context of diseases classified elsewhere",
    "H68 Salpingitis and obstruction of the Eustachian tube",
    "H70 Mastoiditis and related conditions",
    "H71 Cholesteatoma of the middle ear",
    "H72 Perforation of the tympanic membrane",
    "H74 Other diseases of the middle ear and mastoid process",
    "H80 Otosclerosis",
    "H81 Vestibular function impairment",
    "H90 Conductive and sensorineural hearing loss",
    "H92 Ear pain and discharge",
    "H93 Other ear conditions not classified elsewhere",
    "H95 Ear and mastoid process conditions after a diagnostic and therapeutic procedure not classified elsewhere",
    "I00 Acute rheumatic fever without mention of heart involvement",
    "I09.8 Other specified rheumatic heart diseases",
    "I10 Essential hypertension",
    "I11 Hypertensive heart disease",
    "I13 Hypertensive cardionephropathy",
    "I13.9 Hypertensive cardionephropathy unspecified",
    "I15 Secondary hypertension",
    "I20.9 Unspecified angina",
    "I21 Acute myocardial infarction",
    "I24 Other acute ischemic heart diseases",
    "I24.1 Dressler's syndrome",
    "I26 Pulmonary embolism",
    "2017-I26.9 Pulmonary embolism without mention of acute cor pulmonale",
    "I27 Other cardiopulmonary conditions",
    "I27.9 Cardiopulmonary condition unspecified",
    "I28 Other diseases of the pulmonary vessels",
    "I30.0 Idiopathic acute nonspecific pericarditis",
    "I31 Other diseases of the pericardium",
    "I33 Acute and subacute endocarditis",
    "I34 Non-rheumatic lesions of the mitral valve",
    "I40 Acute myocarditis",
    "I42 Cardiomyopathy",
    "I44 Left bundle branch block and atrioventricular block",
    "I47 Paroxysmal tachycardia",
    "I45.8 Other specific conduction disorders",
    "I48 Atrial fibrillation and flutter",
    "I50.0 Congestive heart failure",
    "I49 Other cardiac arrhythmias",
    "I50.1 Left ventricular failure",
    "I50.9 Heart failure unspecified",
    "I60 Subarachnoid hemorrhage",
    "I51 Complications of heart diseases and poorly defined heart diseases",
    "I61 Intracerebral hemorrhage",
    "I61.0 Subcortical hemispheric intracerebral hemorrhage",
    "I61.9 Intracerebral hemorrhage unspecified",
    "I62 Other non-traumatic intracranial hemorrhages",
    "I63 Cerebral infarction",
    "I64 Cerebrovascular accident unspecified as hemorrhagic or infarct",
    "I65 Occlusion and stenosis of precerebral arteries not leading to cerebral infarction",
    "I69 Sequelae of cerebrovascular diseases",
    "I67 Other cerebrovascular diseases",
    "I88 Non-specific lymphadenitis",
    "I70 Atherosclerosis",
    "I71 Aortic aneurysm and dissection",
    "I73 Other peripheral vascular diseases",
    "I74 Arterial embolism and thrombosis",
    "I78 Capillary diseases",
    "I77 Other conditions affecting arteries and arterioles",
    "I84 Hemorrhoids",
    "J01 Acute sinusitis",
    "I80 Phlebitis and thrombophlebitis",
    "J00 Acute rhinitis (common cold)",
    "I81 Portal vein thrombosis",
    "I83 Varicose veins of the lower limbs",
    "I85 Esophageal varices",
    "I95 Hypotension",
    "I98 Other circulatory system disorders in diseases classified elsewhere",
    "J02 Acute pharyngitis",
    "J03 Acute tonsillitis",
    "J04 Acute laryngitis and tracheitis",
    "J05 Acute obstructive laryngitis (croup) and acute epiglottitis",
    "J05.0 Acute obstructive laryngitis (croup)",
    "J05.1 Acute epiglottitis",
    "J11.1 Influenza with other respiratory manifestations, unidentified virus",
    "J10 Influenza due to identified virus",
    "J11.8 Influenza with other manifestations, unidentified virus",
    "J12 Viral pneumonia, not classified elsewhere",
    "J12.9 Viral pneumonia, unspecified",
    "J15 Bacterial pneumonia, not classified elsewhere",
    "J17 Pneumonia in diseases classified elsewhere",
    "J15.9 Bacterial pneumonia, unspecified",
    "J17.0 Pneumonia in bacterial diseases classified elsewhere",
    "J17.3 Pneumopathy in the course of parasitic diseases",
    "J17.8 Pneumopathy in the course of other diseases classified elsewhere",
    "J18.9 Pneumopathy unspecified",
    "J20 Acute bronchitis",
    "J21.9 Unspecified acute bronchiolitis",
    "J30 Allergic and vasomotor rhinitis",
    "J32 Chronic sinusitis",
    "J39 Other diseases of the upper respiratory tract",
    "J33 Nasal polyp",
    "J34 Other diseases of the nose and sinuses",
    "J34.0 Furuncle and anthrax abscess of the nose",
    "J35 Chronic diseases of the tonsils and adenoids",
    "J34.1 Cyst and mucocele of the nose and sinuses",
    "J36 Phlegmonous angina",
    "J37 Chronic laryngitis and laryngotracheitis",
    "J43.0 MacLeod's syndrome",
    "J60 Coal worker's pneumoconiosis",
    "J40 Unspecified bronchitis as acute or chronic",
    "J42 Unspecified chronic bronchitis",
    "J43 Emphysema",
    "J44 Other chronic obstructive pulmonary diseases",
    "J45 Asthma",
    "J85 Lung and mediastinal abscess",
    "J47 Bronchiectasis",
    "J61 Asbestos and other mineral fiber pneumoconiosis",
    "J68 Respiratory conditions due to inhalation of chemical agents, fumes, and gases",
    "J69 Pneumopathy due to solid and liquid substances",
    "J92 Pleural plaque",
    "J90 Pleural effusion, not elsewhere classified",
    "J86 Pyothorax",
    "J96.0 Acute respiratory failure",
    "J93 Pneumothorax",
    "J94 Other pleural conditions",
    "J98 Other respiratory disorders",
    "K00 Dental development disorders",
    "J94.2 Hemothorax",
    "J96.1 Chronic respiratory failure",
    "J96.9 Respiratory failure, unspecified",
    "K00.7 Tooth eruption syndrome",
    "K00.0 Anodontia",
    "K11 Diseases of the salivary glands",
    "K02 Dental caries",
    "K09 Cysts of the oral region not classified elsewhere",
    "K21 Gastroesophageal reflux",
    "K05 Gingivitis and periodontal diseases",
    "K07.6 Temporomandibular joint lesions",
    "K07 Dento-facial anomalies (including malocclusions)",
    "K14 Diseases of the tongue",
    "K13 Other diseases of the lips and buccal mucosa",
    "K20 Esophagitis",
    "K27 Unspecified digestive ulcer",
    "K25 Stomach ulcer",
    "K26 Duodenal ulcer",
    "K29 Gastritis and duodenitis",
    "K31 Other diseases of the stomach and duodenum",
    "K43 Abdominal hernia",
    "K31.0 Acute dilation of the stomach",
    "K35 Acute appendicitis",
    "K41 Femoral hernia",
    "K36 Other forms of appendicitis",
    "K40 Inguinal hernia",
    "K44 Diaphragmatic hernia",
    "K42 Umbilical hernia",
    "K50 Crohn's disease",
    "K51 Ulcerative colitis",
    "K52 Other non-infectious gastroenteritis and colitis",
    "K55 Vascular disorders of the intestine",
    "K58 Irritable bowel syndrome",
    "K56 Paralytic ileus and intestinal obstruction without hernia",
    "K56.4 Other intestinal obstructions",
    "K57 Diverticulosis of the intestine",
    "K62.5 Hemorrhage of the anus and rectum",
    "K59 Other functional intestinal disorders",
    "K60 Anal and rectal fissure and fistula",
    "K62 Other diseases of the anus and rectum",
    "K63 Other diseases of the intestine",
    "K65 Peritonitis",
    "K72.0 Acute and subacute liver failure",
    "K70 Alcoholic liver disease",
    "K71 Toxic liver disease",
    "K72 Unspecified liver failure",
    "K72.1 Chronic liver failure",
    "K72.9 Liver failure unspecified",
    "K73 Chronic hepatitis not elsewhere classified",
    "K74 Liver fibrosis and cirrhosis",
    "K76 Other liver diseases",
    "K80 Gallstones",
    "K81 Cholecystitis",
    "K82 Other diseases of the gallbladder",
    "K86 Other diseases of the pancreas",
    "K85 Acute pancreatitis",
    "K87 Conditions of the gallbladder, bile ducts, and pancreas due to diseases classified elsewhere",
    "K90.9 Unspecified intestinal malabsorption",
    "K90 Malabsorption syndrome",
    "K91 Conditions of the digestive system following diagnostic and therapeutic procedures not elsewhere classified",
    "K91.4 Poor functional outcomes of colostomy and enterostomy",
    "K92 Other diseases of the digestive system",
    "K92.0 Hematemesis",
    "K92.1 Melena",
    "L00 Syndrome of staphylococcal epidermolysis in infants",
    "L01 Impetigo",
    "L02 Cutaneous abscess, furuncle, and anthrax",
    "L04 Acute lymphadenitis",
    "L03 Phlegmon",
    "L05 Pilonidal sinus",
    "L08 Other localized infections of the skin and subcutaneous cellular tissue",
    "L10 Pemphigus",
    "L11 Other acantholyses",
    "L13 Other blistering dermatoses",
    "L20 Atopic dermatitis",
    "L21 Seborrheic dermatitis",
    "L22 Diaper dermatitis in infants",
    "L23 Allergic contact dermatitis",
    "L25 Contact dermatitis unspecified",
    "L25.0 Unspecified contact dermatitis due to cosmetics",
    "L26 Exfoliative dermatitis",
    "L29 Pruritus",
    "L30 Other dermatitis",
    "L30.1 Dyshidrosis (pompholyx)",
    "L40 Psoriasis",
    "L41 Parapsoriasis",
    "L42 Pityriasis rosea",
    "L43 Lichen planus",
    "L50 Urticaria",
    "L51 Erythema multiforme",
    "L52 Nodular erythema",
    "L53 Other forms of erythema",
    "L70 Acne",
    "L60.1 Onycholysis",
    "L55 Sunburn",
    "L68 Hypertrichosis",
    "L60 Nail diseases",
    "L60.0 Ingrown nail",
    "L63 Alopecia areata",
    "L60.8 Other nail diseases",
    "L72 Follicular cysts of the skin and subcutaneous tissue",
    "L64 Androgenetic alopecia",
    "L73 Other follicular conditions",
    "L91 Hypertrophic skin disorders",
    "L80 Vitiligo",
    "L74 Disorders of sweat glands",
    "L81 Other pigmentation anomalies",
    "L90 Atrophic skin disorders",
    "L82 Seborrheic keratosis",
    "L84 Corns and calluses",
    "L85 Other thickening of the epidermis",
    "L89 Pressure ulcers",
    "L92 Granulomatous lesions of the skin and subcutaneous tissue",
    "L93 Systemic lupus erythematosus",
    "L95 Vasculitis limited to the skin not classified elsewhere",
    "L97 Lower limb ulcer not classified elsewhere",
    "M00 Pyogenic bacterial arthritis",
    "M01 Direct infectious arthritis during infectious and parasitic diseases classified elsewhere",
    "M05 Seropositive rheumatoid arthritis",
    "M06 Other rheumatoid arthritis",
    "M08 Juvenile arthritis",
    "M10 Gout",
    "M11 Other arthropathies due to microcrystals",
    "M15 Polyarthritis",
    "M16 Coxarthrosis (hip arthritis)",
    "M17 Gonarthrosis (knee arthritis)",
    "M19 Other arthroses",
    "M20 Deformations of the fingers and toes",
    "M21 Other deformations of the limbs",
    "M22 Patellar lesion",
    "M23 Internal knee lesion",
    "M25 Other unspecified joint conditions",
    "M24 Other specific joint conditions",
    "M25.4 Joint effusion",
    "M25.5 Joint pain",
    "M30 Nodular periarteritis and related conditions",
    "M32 Systemic lupus erythematosus",
    "M31 Other necrotizing vasculopathies",
    "M33 Dermatomyositis",
    "M34 Systemic sclerosis",
    "M35 Other systemic connective tissue disorders",
    "M40 Kyphosis and lordosis",
    "M41 Scoliosis",
    "M42 Vertebral osteochondritis",
    "M43 Other dorsopathies with deformation",
    "M45 Ankylosing spondylitis",
    "M47 Spondyloarthrosis",
    "M48 Other spondyloathies",
    "M49 Spondyloarthropathies due to diseases classified elsewhere",
    "M50 Cervical disc disorders",
    "M53 Other dorsopathies not classified elsewhere",
    "M51 Other intervertebral disc disorders",
    "M54 Back pain",
    "M60 Myositis",
    "M62 Other muscle disorders",
    "M62.5 Muscle atrophy and wasting not classified elsewhere",
    "M65 Synovitis and tenosynovitis",
    "M66 Spontaneous rupture of synovial tissue and tendon",
    "M75 Shoulder injuries",
    "M77 Other enthesopathies",
    "M79 Other soft tissue disorders not classified elsewhere",
    "M79.5 Residual foreign body in soft tissue",
    "M80 Osteoporosis with pathological fracture",
    "M82 Osteoporosis in diseases classified elsewhere",
    "M81 Osteoporosis without pathological fracture",
    "M84 Bone continuity disorders",
    "M87 Osteonecrosis",
    "M85 Other abnormalities of bone density",
    "N13 Obstructive uropathy and reflux",
    "M86 Osteomyelitis",
    "N00 Acute nephritic syndrome",
    "M95 Other deformities of the osteoarticular system, muscles, and connective tissue",
    "M96 Conditions of the osteoarticular system and muscles after a diagnostic and therapeutic procedure not classified elsewhere",
    "M99 Biomechanical lesions not classified elsewhere",
    "N02 Recurrent and persistent hematuria",
    "N04 Nephrotic syndrome",
    "N17 Acute renal failure",
    "N10 Acute tubulointerstitial nephritis",
    "N14 Tubulointerstitial and tubular injuries due to drugs and heavy metals",
    "N15 Other tubulointerstitial kidney diseases",
    "N15.1 Renal and perirenal abscess",
    "N18.0 End-stage renal failure",
    "N18 Chronic renal failure",
    "N20 Calculus of the kidney and ureter",
    "N21 Calculus of the lower urinary tract",
    "N22 Calculus of the urinary tract due to diseases classified elsewhere",
    "N23 Nephritic colic unspecified",
    "N28 Other conditions of the kidney and ureter not classified elsewhere",
    "N30 Cystitis",
    "N31 Neuromuscular dysfunction of the bladder",
    "N32 Other conditions of the bladder",
    "N34 Urethritis and urethral syndrome",
    "N35 Urethral stricture",
    "N36 Other conditions of the urethra",
    "N39 Other conditions of the urinary system",
    "N40 Benign prostatic hyperplasia",
    "N41 Inflammatory diseases of the prostate",
    "N42 Other conditions of the prostate",
    "N43 Hydrocele and spermatocele",
    "N44 Testicular torsion",
    "N45 Orchitis and epididymitis",
    "N46 Male infertility",
    "N47 Hypertrophy of the prepuce, phimosis, and paraphimosis",
    "N48 Other conditions of the penis",
    "N48.3 Priapism",
    "N48.4 Organic impotence",
    "N49 Inflammatory conditions of the male genital organs not elsewhere classified",
    "N50 Other conditions of the male genital organs",
    "N60 Benign breast dysplasias",
    "N61 Inflammatory conditions of the breast",
    "N62 Breast hypertrophy",
    "N63 Breast lump unspecified",
    "N76 Other inflammations of the vagina and vulva",
    "N64 Other breast conditions",
    "N70 Salpingitis and oophoritis",
    "N71 Inflammatory conditions of the uterus excluding the cervix",
    "N80 Endometriosis",
    "N72 Inflammatory conditions of the cervix",
    "N73 Other pelvic inflammatory conditions in women",
    "N82 Fistulas of the female genitals",
    "N75 Bartholin gland disorder",
    "N83 Non-inflammatory conditions of the ovary, fallopian tube, and broad ligament",
    "N84 Polyp of the female genital tract",
    "N81 Genital prolapse",
    "N85 Other non-inflammatory conditions of the uterus except the cervix",
    "N86 Erosion and ectropion of the cervix",
    "N87 Cervical dysplasia",
    "N88 Other non-inflammatory conditions of the cervix",
    "N89 Other non-inflammatory conditions of the vagina",
    "N90 Other non-inflammatory conditions of the vulva and perineum",
    "N91 Amenorrhea, oligomenorrhea, and hypomenorrhea",
    "N92 Menorrhagia, polymenorrhea, and metrorrhagia",
    "N94 Pain and other conditions of the female genital organs and menstrual cycle",
    "N94.0 Intermenstrual pain",
    "N94.1 Dyspareunia",
    "N94.2 Vaginismus",
    "N94.5 Secondary dysmenorrhea",
    "N94.3 Premenstrual tension syndrome",
    "N94.4 Primary dysmenorrhea",
    "N95 Menopause disorders and other perimenopause disorders",
    "N96 Recurrent abortions",
    "O01 Hydatidiform mole",
    "N97 Female infertility",
    "N99 Conditions of the genitourinary system following a diagnostic or therapeutic procedure not elsewhere classified",
    "O00 Ectopic pregnancy",
    "O02 Other abnormal products of conception",
    "O03 Spontaneous abortion",
    "O04 Medical abortion",
    "O06 Abortion without specification",
    "O07 Failure of an abortion attempt",
    "O08 Complications following an abortion, ectopic pregnancy, and molar pregnancy",
    "O10 Preexisting hypertension complicating pregnancy, childbirth, and the puerperium",
    "O11 Preexisting hypertensive syndrome with added proteinuria",
    "O14 Gestational hypertension [related to pregnancy] with significant proteinuria",
    "O12 Gestational edema and proteinuria [related to pregnancy] without hypertension",
    "O13 Gestational hypertension (related to pregnancy) without significant proteinuria",
    "O21 Intractable vomiting during pregnancy",
    "O14.0 Moderate preeclampsia",
    "O14.1 Severe preeclampsia",
    "O15 Eclampsia",
    "O25 Malnutrition during pregnancy",
    "O20 Bleeding in early pregnancy",
    "O22 Venous complications of pregnancy",
    "O23 Genitourinary infections during pregnancy",
    "O24 Diabetes during pregnancy",
    "O28 Abnormal results observed during the systematic prenatal examination of the mother",
    "O26 Maternal care for other conditions primarily related to pregnancy",
    "O29 Complication of anesthesia during pregnancy",
    "O30 Multiple pregnancy",
    "O36 Maternal care for other known or presumed conditions of the fetus",
    "O35 Maternal care for known or presumed fetal anomalies and lesions",
    "O33 Maternal care for known or presumed fetal-pelvic disproportion",
    "O34 Maternal care for known or presumed abnormalities of the pelvic organs",
    "O31 Other complications specific to multiple pregnancy",
    "O32 Maternal care for known or presumed abnormal presentation of the fetus",
    "O40 Hydramnios",
    "O41 Other anomalies of amniotic fluid and membranes",
    "O43 Placental anomalies",
    "O42 Premature rupture of membranes",
    "O47 False labor",
    "O44 Placenta previa",
    "O45 Premature separation of the placenta [retro-placental hematoma]",
    "O60 Premature labor",
    "O61 Failed induction",
    "O46 Bleeding before delivery not classified elsewhere",
    "O62 Uterine contraction and cervical dilation anomalies",
    "O48 Prolonged pregnancy",
    "O63 Prolonged labor",
    "O64 Dystocia due to abnormal fetal position and presentation",
    "O65 Dystocia due to maternal pelvic anomaly",
    "O66 Other dystocias",
    "O67 Labor and delivery complicated by unspecified hemorrhage",
    "O68 Labor and delivery complicated by fetal distress",
    "O69 Labor and delivery complicated by umbilical cord anomalies",
    "O70 Obstetric tear of the perineum",
    "O71 Other obstetric trauma",
    "O71.1 Uterine rupture during labor",
    "O72 Postpartum hemorrhage",
    "O73 Retention of placenta and membranes without hemorrhage",
    "O74 Complications of anesthesia during labor and delivery",
    "O75 Other complications of labor and delivery not classified elsewhere",
    "O80 Single spontaneous delivery",
    "O81 Single delivery by forceps and vacuum extraction",
    "O82 Single birth by cesarean section",
    "O83 Other single births with assistance",
    "O84 Multiple births",
    "O84.0 All multiples spontaneous",
    "O84.1 All multiples by forceps and vacuum",
    "O84.2 All multiples by cesarean section",
    "O85 Puerperal sepsis",
    "O84.8 Other multiple births",
    "O86 Other puerperal infections",
    "O87 Venous complications during the puerperium",
    "O89 Anesthesia complications during the puerperium",
    "O88 Obstetric embolism",
    "O90 Puerperal complications not classified elsewhere",
    "O91 Breast infections associated with childbirth",
    "O92 Other mastopathies and lactation anomalies associated with childbirth",
    "O94 Sequelae of complications from pregnancy, childbirth, and the puerperium",
    "O95 Obstetrical death of unspecified cause",
    "O96 Obstetrical death occurring more than 42 days and less than one year after childbirth",
    "O97 Death from sequelae directly related to an obstetrical cause",
    "O98 Infectious and parasitic diseases of the mother classified elsewhere complicating pregnancy, childbirth, and the puerperium",
    "O99.0 Anemia complicating pregnancy, delivery, and the puerperium",
    "O99 Other maternal diseases classified elsewhere but complicating pregnancy, delivery, and the puerperium",
    "P00 Fetus and newborn affected by maternal conditions possibly unrelated to the current pregnancy",
    "P00.8 Fetus and newborn affected by other maternal conditions",
    "P03 Fetus and newborn affected by other complications of labor and delivery",
    "P05 Fetal growth retardation and malnutrition",
    "P07 Anomalies related to short gestation and low birth weight not classified elsewhere",
    "P08 Anomalies related to prolonged gestation and high birth weight",
    "P10 Intracranial hemorrhage and tears due to obstetrical trauma",
    "P14 Peripheral nervous system injury due to obstetrical trauma",
    "P15.9 Obstetrical trauma unspecified",
    "P20 Intrauterine hypoxia",
    "P21 Obstetric asphyxia",
    "P22 Respiratory distress in the newborn",
    "P24 Neonatal aspiration syndromes",
    "P24.0 Neonatal aspiration of meconium",
    "P24.8 Other neonatal aspiration syndromes",
    "P28 Other respiratory conditions occurring during the perinatal period",
    "P35 Congenital viral diseases",
    "P29 Cardiovascular conditions occurring during the perinatal period",
    "P36 Bacterial infection in the newborn",
    "P38 Omphalitis in the newborn with or without slight bleeding",
    "P50 Fetal blood loss",
    "P55 Hemolytic disease of the fetus and newborn",
    "P57 Kernicterus",
    "P59 Neonatal jaundice due to other causes and unspecified",
    "P60 Disseminated intravascular coagulation in the fetus and newborn",
    "P61 Other hematological conditions of the perinatal period",
    "P71 Transient anomalies of calcium and magnesium metabolism in the newborn",
    "P70 Transient anomalies of carbohydrate metabolism specific to the fetus and newborn",
    "P74 Other transient electrolyte and metabolic anomalies in the newborn",
    "P80 Hypothermia in the newborn",
    "P91 Other brain conditions in the newborn",
    "P92 Feeding problems in the newborn",
    "Q00 Anencephaly and similar malformations",
    "Q03 Congenital hydrocephalus",
    "Q05 Spina bifida",
    "Q10 Congenital malformations of the eyelids, lacrimal apparatus, and orbit",
    "Q16 Congenital malformations of the ear with hearing impairment",
    "Q18 Other congenital malformations of the face and neck",
    "Q20 Congenital malformations of the heart cavities and orifices",
    "Q25 Congenital malformations of large vessels",
    "Q30 Congenital malformations of the nose",
    "Q31 Congenital malformations of the larynx",
    "Q35 Cleft palate",
    "Q36 Cleft lip",
    "Q37 Cleft lip and palate",
    "Q38 Other congenital malformations of the tongue, mouth, and pharynx",
    "Q39 Congenital malformations of the esophagus",
    "Q40.1 Congenital hiatal hernia",
    "Q40.0 Hypertrophic pyloric stenosis",
    "Q40 Other congenital malformations of the upper digestive tract",
    "Q41 Congenital absence, atresia, and stenosis of the small intestine",
    "Q42 Congenital absence, atresia, and stenosis of the colon",
    "Q42.2 Congenital absence, atresia, and stenosis of the anus with fistulas",
    "Q42.3 Congenital absence, atresia, and stenosis of the anus without fistulas",
    "Q43 Other congenital malformations of the intestine",
    "Q43.0 Meckel's diverticulum",
    "Q44 Congenital malformations of the gallbladder, bile ducts, and liver",
    "Q43.1 Hirschsprung's disease",
    "Q45 Other congenital malformations of the digestive system",
    "Q50 Congenital malformations of the ovaries, fallopian tubes, and broad ligaments",
    "Q51 Malformations of the uterus and cervix",
    "Q52 Other congenital malformations of the female genital organs",
    "Q52.0 Congenital absence of the vagina",
    "Q52.3 Imperforate hymen",
    "Q53 Cryptorchidism",
    "Q54 Hypospadias",
    "Q56 Sexual differentiation disorder and pseudohermaphroditism",
    "Q60 Renal agenesis and other renal developmental defects",
    "Q61 Cystic kidney diseases",
    "Q65 Congenital morphological anomalies of the hip",
    "Q66 Congenital morphological anomalies of the foot",
    "Q67 Congenital morphological anomalies of the head, face, spine, and thorax",
    "Q68 Other congenital morphological anomalies of the musculoskeletal system and muscles",
    "Q69 Polydactyly",
    "Q79 Congenital malformations of the musculoskeletal system and muscles not classified elsewhere",
    "Q89 Other congenital malformations not classified elsewhere",
    "Q90 Down syndrome",
    "R00.0 Tachycardia unspecified",
    "R00 Cardiac rhythm abnormalities",
    "R00.8 Other and unspecified cardiac rhythm anomalies",
    "R02 Unclassified gangrene",
    "R01 Murmurs and other heart sounds",
    "R03 Finding of blood pressure anomaly without diagnosis",
    "R04 Hemorrhage of the respiratory tract",
    "R04.0 Nosebleed",
    "R04.2 Hemoptysis",
    "R06 Respiratory anomalies",
    "R07 Throat and chest pain",
    "R09 Other symptoms and signs related to the circulatory and respiratory systems",
    "R10 Abdominal and pelvic pain",
    "R11 Nausea and vomiting",
    "R12 Heartburn",
    "R13 Dysphagia",
    "R14 Flatulence and apparent disorders",
    "R15 Fecal incontinence",
    "R16 Unclassified hepatomegaly and splenomegaly",
    "R18 Ascites",
    "R19 Other symptoms and signs related to the digestive system and abdomen",
    "R20 Skin sensitivity disorders",
    "R22 Other localized swellings and masses of the skin and subcutaneous tissue",
    "R21 Rash and other nonspecific skin eruptions",
    "R23 Other skin changes",
    "R26 Gait and mobility abnormalities",
    "R29 Other symptoms and signs related to the nervous system and musculoskeletal system",
    "R30 Pain during urination",
    "R31 Hematuria unspecified",
    "R32 Urinary incontinence unspecified",
    "R33 Urinary retention",
    "R34 Anuria and oliguria",
    "R35 Polyuria",
    "R36 Urethral discharge",
    "R39 Other symptoms and signs related to the urinary system",
    "R40 Drowsiness stupor and coma",
    "R41 Other symptoms and signs related to cognitive functions and consciousness",
    "R42 Dizziness and lightheadedness",
    "R43 Olfactory and taste disorders",
    "R45 Symptoms and signs related to mood",
    "R44 Other symptoms and signs related to general sensations and perceptions",
    "R46 Symptoms and signs related to appearance and behavior",
    "R47 Speech disorders not classified elsewhere",
    "R49 Voice disorders",
    "R50 Fever of unknown origin",
    "R51 Headache",
    "R52 Pain not classified elsewhere",
    "R53 Malaise and fatigue",
    "R54 Senility",
    "R55 Syncope and collapse",
    "R56 Seizures not classified elsewhere",
    "R57 Shock not classified elsewhere",
    "R58 Hemorrhage not classified elsewhere",
    "R59 Lymphadenopathy",
    "R60 Edema not classified elsewhere",
    "R61 Hyperhidrosis",
    "R62 Delay in physiological development",
    "R63 Symptoms and signs related to food and fluid absorption",
    "R64 Cachexia",
    "R68 Other general symptoms and signs",
    "R69 Unknown and unspecified causes of morbidity",
    "R71 Anomalies of red blood cells",
    "R73 Increased blood sugar",
    "R75 Laboratory confirmation of human immunodeficiency virus (HIV)",
    "R80 Isolated proteinuria",
    "R83 Abnormal results of cerebrospinal fluid examination",
    "R90 Abnormal results from central nervous system imaging",
    "R94 Abnormal functional exploration results",
    "R95 Sudden infant death syndrome",
    "S00 Superficial traumatic injury to the head",
    "S01 Open wound of the head",
    "S02 Fracture of the skull and facial bones",
    "S03 Dislocation, sprain, and strain of joints and ligaments in the head",
    "S04 Traumatic injury to cranial nerves",
    "S05 Traumatic injury to the eye and orbit",
    "S06 Intracranial traumatic injury",
    "S07 Crushing of the head",
    "S08 Traumatic amputation of a part of the head",
    "S11 Open wound of the neck",
    "S12 Fracture of the neck",
    "S13 Dislocation, sprain, and strain of ligaments in the neck",
    "S17 Crush injury of the neck",
    "S30 Superficial traumatic lesion of the abdomen, lower back, and pelvis",
    "S31 Open wound of the abdomen, lower back, and pelvis",
    "S36 Traumatic lesion of intra-abdominal organs",
    "S31.4 Open wound of the vagina and vulva",
    "S37 Traumatic lesion of pelvic organs",
    "S37.0 Traumatic lesion of the kidney",
    "S52 Fracture of the forearm",
    "S53 Dislocation, sprain, and strain of the elbow joints and ligaments",
    "S54 Traumatic nerve injury at the forearm",
    "S58 Traumatic amputation of the forearm",
    "S60 Superficial traumatic lesion of the wrist and hand",
    "S61 Open wound of the wrist and hand",
    "S64 Traumatic nerve injury at the wrist and hand",
    "S62 Fracture of the wrist and hand",
    "S65 Traumatic injury of blood vessels at the wrist and hand",
    "S66 Traumatic injury of muscles and tendons at the wrist and hand",
    "S67 Crush injury of the wrist and hand",
    "S68 Traumatic amputation of the wrist and hand",
    "S70 Superficial traumatic lesion of the hip and thigh",
    "S71 Open wound of the hip and thigh",
    "S72 Fracture of the femur",
    "S74 Traumatic nerve injury at the hip and thigh",
    "S73 Dislocation, sprain, and strain of the hip joint and ligaments",
    "S75 Traumatic vascular injury at the hip and thigh",
    "S76 Traumatic injury of muscles and tendons at the hip and thigh",
    "S78 Traumatic amputation of the hip and thigh",
    "S77 Crush injury of the hip and thigh",
    "S79 Other unspecified traumatic lesions of the hip and thigh",
    "S82 Fracture of the leg including the ankle",
    "S81 Open wound of the leg",
    "S80 Superficial traumatic injury of the leg",
    "S83.2 Recent tear of a meniscus",
    "S83 Dislocation, sprain, and strain of the knee joint and ligaments",
    "S84 Traumatic nerve injury at the leg",
    "S85 Traumatic vascular injury at the leg",
    "S86 Traumatic injury of muscles and tendons at the leg",
    "S87 Crush injury of the leg",
    "S88 Traumatic amputation of the leg",
    "S89 Other unspecified traumatic lesions of the leg",
    "S90 Superficial traumatic lesion of the ankle and foot",
    "S91 Open wound of the ankle and foot",
    "S93 Dislocation, sprain, and strain of the joints and ligaments in the ankle and foot",
    "S95 Traumatic injury of blood vessels in the ankle and foot",
    "S96 Traumatic injury of muscles and tendons in the ankle and foot",
    "S97 Crushing of the ankle and foot",
    "S98 Traumatic amputation of the ankle and foot",
    "T00 Superficial traumatic lesions of multiple body parts",
    "T01 Open wounds of multiple body parts",
    "T02 Fractures of multiple body parts",
    "T04 Crush injuries of multiple body parts",
    "T05 Traumatic amputations of multiple body parts",
    "T14 Traumatic injuries of a part of the body unspecified",
    "T15 Foreign body in the external part of the eye",
    "T20 Burn and corrosion of the head and neck",
    "T21 Burn and corrosion of the trunk",
    "T22 Burn and corrosion of the shoulder and upper limb except for wrist and hand",
    "T23 Burn and corrosion of the wrist and hand",
    "T24 Burn and corrosion of the hip and lower limb except for ankle and foot",
    "T25 Burn and corrosion of the ankle and foot",
    "T30 Burn and corrosion of unspecified body part",
    "T32 Corrosions classified according to the extent of the affected body surface",
    "T36 Intoxication by systemic antibiotics",
    "T37 Intoxication by other systemic anti-infectives and antiparasitics",
    "T38 Intoxication by hormones and their synthetic substitutes and antagonists",
    "T41 Intoxication by anesthetics and therapeutic gases",
    "T42 Intoxication by sedative hypnotics, anti-epileptics, and anti-Parkinsonian drugs",
    "T43 Intoxication by psychotropic medications not classified elsewhere",
    "T44 Intoxication by medications acting on the autonomic nervous system",
    "T45 Intoxication by systemic and hematological substances",
    "T46 Intoxication by substances primarily affecting the cardiovascular system",
    "T50 Intoxication by diuretics and other biological medications and substances",
    "T51 Toxic effect of alcohol",
    "T53 Toxic effect of halogenated derivatives of aliphatic and aromatic hydrocarbons",
    "T54 Toxic effect of corrosive substances",
    "2017-T55 Toxic effect of soaps and detergents",
    "2017-T58 Toxic effect of carbon monoxide",
    "T60 Toxic effect of pesticides",
    "T62 Toxic effect of other harmful substances absorbed through food",
    "T63 Toxic effect of contact with a venomous animal",
    "T66 Effects of radiation unspecified",
    "T67 Effects of heat and light",
    "T70 Effects of atmospheric pressure and water pressure",
    "T71 Asphyxia",
    "T73 Effects of other deprivations",
    "T74 Syndromes due to mistreatment",
    "T74.0 Neglect and abandonment",
    "T74.1 Physical abuse",
    "T74.2 Sexual abuse",
    "T74.3 Psychological abuse",
    "T75 Effects of other external causes",
    "T78 Undesirable effects not classified elsewhere",
    "T79 Certain early complications of trauma not classified elsewhere",
    "T80 Complications following therapeutic injection, infusion, and transfusion",
    "T81 Complications of diagnostic and therapeutic procedures not classified elsewhere",
    "T82 Complications of cardiac and vascular prostheses, implants, and grafts",
    "T84 Complications of orthopedic internal prostheses, implants, and grafts",
    "T86 Failure and rejection of organ and tissue transplants",
    "T87 Complications specific to reimplantation and amputation",
    "T88 Other complications of surgical and medical care not classified elsewhere",
    "T90 Sequelae of traumatic lesions of the head",
    "T91 Sequelae of traumatic lesions of the neck and trunk",
    "T92 Sequelae of traumatic lesions of the upper limb",
    "T93 Sequelae of traumatic lesions of the lower limb",
    "T94 Sequelae of traumatic lesions of multiple and unspecified body parts",
    "T95 Sequelae of burns, corrosions, and frostbite",
    "T96 Sequelae of poisoning by medications and biological substances",
    "U80 Agents resistant to penicillin and related",
    "2017-U81 Agents resistant to vancomycin and related",
    "U88 Agents resistant to multiple antibiotics",
    "W22 Impact against or by other objects",
    "U89 Agents resistant to other and unspecified antibiotics",
    "V99 Transport accident unspecified",
    "W19 Fall unspecified",
    "W49 Exposure to mechanical forces other and unspecified",
    "W51 Collision between two people",
    "W54 Bite or scratch inflicted by a dog",
    "W74 Drowning and submersion unspecified",
    "W87 Exposure to electric current unspecified",
    "X09 Exposure to smoke, fire, and flames unspecified",
    "X20 Contact with venomous snakes and lizards",
    "X30 Exposure to excessive natural heat",
    "2017-X34 Earthquake",
    "X44 Accidental poisoning by other unspecified medications and biological substances, and exposure to these products",
    "X49 Accidental poisoning by chemicals and harmful substances, and exposure to other unspecified products",
    "X59 Exposure to unspecified factors",
    "X69 Self-poisoning by chemicals and harmful substances, and exposure to other unspecified products",
    "2017-X70 Self-inflicted injury by hanging, strangulation, and suffocation",
    "X71 Self-inflicted injury by drowning and submersion",
    "2017-X76 Self-inflicted injury by exposure to smoke, fire, and flames",
    "X95 Assault by unspecified firearm",
    "X98 Assault by steam, gases, and burning objects",
    "X99 Assault by sharp object",
    "Y00 Assault by blunt object",
    "Y07 Other maltreatment",
    "Y08 Assault by other specified means",
    "Y09 Assault by unspecified means",
    "Y12 Intoxication by narcotics and psychedelic substances",
    "Y15 Intoxication by alcohol and exposure to alcohol, intent unspecified",
    "Y34 Event with unspecified intent, intent unspecified",
    "2017-Y35 Intervention by public force",
    "2017-Y36 Acts of war",
    "Z00 General examination and investigations of individuals with no complaints or for whom no diagnosis is reported",
    "Y62 Insufficient asepsis during medical and surgical procedures",
    "Z01 Other special examinations and investigations of individuals with no complaints or for whom no diagnosis is reported",
    "Z02 Medical examination and contact for administrative purposes",
    "Z03 Observation and medical examination for suspicion of diseases",
    "Z04 Examination and observation for other reasons",
    "Z08 Follow-up examination after treatment of a malignant tumor",
    "Z10 Routine general examination of a defined subpopulation",
    "Z11 Special screening examination for infectious and parasitic diseases",
    "Z20 Individuals in contact with and exposed to transmissible diseases",
    "Z30 Management of contraception",
    "Z31 Reproductive measures",
    "Z32 Pregnancy examination and testing",
    "Z34 Monitoring of a normal pregnancy",
    "Z40 Prophylactic operation",
    "Z41 Therapy without medical reason",
    "Z42 Follow-up care including plastic surgery",
    "Z43 Monitoring of stomas",
    "Z46 Placement and adjustment of other devices",
    "2017-Z55 Difficulties related to education and literacy",
    "Z56 Difficulties related to employment and unemployment",
    "2017-Z58 Difficulties related to the physical environment",
    "2017-Z59 Difficulties related to housing and economic conditions",
    "Z60 Difficulties related to the social environment",
    "Z63 Other difficulties related to the immediate surroundings including family situation",
    "Z64 Difficulties related to certain psychosocial situations",
    "Z65 Difficulties related to other psychosocial situations",
    "Z70 Advice regarding attitudes, behavior, and orientation in matters of sexuality",
    "Z72 Difficulties related to lifestyle",
    "Z71 Individuals in contact with health services for other advice and medical opinions not classified elsewhere",
    "2017-Z72.0 Tobacco use",
    "Z73 Difficulties related to lifestyle orientation",
    "Z74 Difficulties related to dependence on the caregiver",
    "Z75 Difficulties related to medical facilities and other health care",
    "Z80 Family history of malignant tumors",
    "Z82 Family history of certain disabilities and chronic diseases leading to disability",
    "Z91 Personal history of risk factors not classified elsewhere",
    "Z93 Stomies",
    "Z99 Dependence on machines and auxiliary devices not classified elsewhere",
]


CONCEPTS_TO_VALIDATE = [
    ConceptDefinition(name="Weight", datatype="Numeric"),
    ConceptDefinition(name="Height"),
    ConceptDefinition(name="Blood Pressure", datatype="Text"),
    # Add more concepts as needed
]

# OpenMRS connection settings
OPENMRS_BASE_URL = "http://uvl-emr.madiro.org"
OPENMRS_USERNAME = "admin"
OPENMRS_PASSWORD = "Admin123"
OPENMRS_COOKIES = {"JSESSIONID": "727055613C7544EA04B91FE35E3B376C"}
